"""esquema inicial

Revision ID: 257dd651aca3
Revises: 
Create Date: 2026-09-16 01:42:54.855828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257dd651aca3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_contas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('natureza', sa.String(length=10), nullable=False),
    sa.Column('sintetica', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("natureza IN ('DEVEDORA','CREDORA')", name='ck_plano_contas_natureza'),
    sa.CheckConstraint("tipo IN ('ATIVO','PASSIVO','PATRIMONIO_LIQUIDO','RECEITA','DESPESA')", name='ck_plano_contas_tipo'),
    sa.ForeignKeyConstraint(['parent_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_plano_contas_codigo')
    )
    with op.batch_alter_table('plano_contas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_contas_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_plano_contas_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plano_contas_parent_id'), ['parent_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('contas_correntes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('banco', sa.String(length=50), nullable=False),
    sa.Column('agencia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('moeda', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_saldo_inicial', sa.Date(), nullable=False),
    sa.Column('plano_conta_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plano_conta_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banco', 'agencia', 'numero', name='uq_conta_banco_agencia_numero')
    )
    with op.batch_alter_table('contas_correntes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_correntes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contas_correntes_plano_conta_id'), ['plano_conta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas_correntes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_correntes_plano_conta_id'))
        batch_op.drop_index(batch_op.f('ix_contas_correntes_deleted_at'))

    op.drop_table('contas_correntes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('plano_contas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_contas_parent_id'))
        batch_op.drop_index(batch_op.f('ix_plano_contas_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_plano_contas_codigo'))

    op.drop_table('plano_contas')
    # ### end Alembic commands ###
